### ISSUE TITLE
For adding topic wise DSA Solved Problems in Java

### ISSUE THREAD

**Issue by ArunBalajiR** [Uniq-dev/hacktober2021#68]
Hey, I'd like to contribute by adding topic wise DSA Solved Problems in JAVA . Would you assign me ?

**Comment by heenahmed** [comment]
plz assign me this issue

**Comment by apmit2704** [comment]
Add binary search in Java.
Please assign me this issue

**Comment by staykirak** [comment]
I want to work on this please assign me
