### ISSUE TITLE
perform bubble sort

### ISSUE THREAD

**Issue by Uniq-dev** [Uniq-dev/hacktober2021#9]

**Comment by ayushjindal23** [comment]
Can you assign this to me?

**Comment by Uniq-dev** [comment]
Assigned to @ayushjindal23. Add screenshot of any test case

**Comment by ayushjindal23** [comment]
![test case](https://user-images.githubusercontent.com/64908612/135722436-63ffe276-7e1b-45e2-a018-f0926d731609.png)

**Comment by ayushjindal23** [comment]
@Uniq-dev

**Comment by eeshita19** [comment]
Please create a PR

**Comment by Uniq-dev** [comment]
Please create a PR
